source 'https://rubygems.org'

gem 'sinatra'
gem 'rspec'
gem 'capybara'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'dm-sqlite-adapter'
gem 'json'
gem 'paperclip'
gem 'rmagick'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-paperclip'
gem 'aws-s3'
